### ISSUE TITLE
Create warp gate model + textures

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#13]

**Comment by fabulous999** [comment]
![gate3](https://cloud.githubusercontent.com/assets/13458986/20849470/d7e353d8-b8a4-11e6-811d-3603cf6ba1b5.png)
![gate2](https://cloud.githubusercontent.com/assets/13458986/20849472/d7e481c2-b8a4-11e6-8b1c-dd597d238b7b.png)
![gate4](https://cloud.githubusercontent.com/assets/13458986/20849471/d7e3c0ac-b8a4-11e6-8b51-706ddf0a7a15.png)
![gate1](https://cloud.githubusercontent.com/assets/13458986/20849473/d7e53112-b8a4-11e6-8576-741d0cd796fd.png)

**Comment by angelinagutz** [comment]
@fabulous999 the models don't seem to be on the repository; could you provide them?
