### ISSUE TITLE
Create vehicle interior model + textures

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#14]

**Comment by fabulous999** [comment]
[ship.zip](https://github.com/MWMaresch/Space-Chase-VR/files/502772/ship.zip)

the final result for the ship tell me if everything is good with it or what need to change?

**Comment by fabulous999** [comment]
![afawfwqfqw](https://cloud.githubusercontent.com/assets/13458986/18990296/e8dd7bfc-86de-11e6-9f3b-0c6bced4f885.png)
![asfafafasfasf](https://cloud.githubusercontent.com/assets/13458986/18990298/e8eac000-86de-11e6-9b63-b1c4eaf80561.png)
![afsafqwfqwfqwfqwgqwg](https://cloud.githubusercontent.com/assets/13458986/18990297/e8eac0c8-86de-11e6-9a3a-420d62626a06.png)
![afasfafwqqwtqgvdxbxcv](https://cloud.githubusercontent.com/assets/13458986/18990300/e8f8d76c-86de-11e6-8256-0c38e5fe6fe1.png)
![afqwfqwfsvxzvvzvz](https://cloud.githubusercontent.com/assets/13458986/18990299/e8f608ca-86de-11e6-8183-7a36b2286711.png)

**Comment by MWMaresch** [comment]
Closing this because further enhancements belong to #32 , and also to show we made progress for the milestone.
