### ISSUE TITLE
Implement player health + crashing

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#2]

**Comment by gsavchenko** [comment]
Created a 'Vehicle' script for the vehicle and added collision detect such that it detects a collision at a time to drain the ship's total health. Waiting on basic control functions to be implemented to fully integrate.

**Comment by gsavchenko** [comment]
Functionality is complete. User-interface needs to be added to reflect this.

**Comment by gsavchenko** [comment]
Basic functionality added.
