### ISSUE TITLE
Create level concept art

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#3]

**Comment by angelinagutz** [comment]
![something for software project 6](https://cloud.githubusercontent.com/assets/13426919/19357893/89c04920-9141-11e6-814a-3ad910562a27.png)

Side view of a level.

P = player
E = enemy
C = Bystander ship

![something for software project 7](https://cloud.githubusercontent.com/assets/13426919/19357892/89ba78c4-9141-11e6-9dd8-829991e52011.png)

View of level from the back/inside the ship.
(Buildings are in purple, bystander ships are in gold, slipstream is in red)

![something for software project 8](https://cloud.githubusercontent.com/assets/13426919/19357891/89b7686e-9141-11e6-92c8-32f87c62043c.png)

A possible map of a level.

(Buildings are in purple, bystander ships are in gold, enemy ship is red, player ship is blue, warp gate is green)

**Comment by MWMaresch** [comment]
I'll start #11 with this

**Comment by MWMaresch** [comment]
Finished #11 , therefore this should be closed too. Further improvements belong to #32
