### ISSUE TITLE
Create vehicle concept art

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#4]

**Comment by angelinagutz** [comment]
![Vehicle Concept](https://cloud.githubusercontent.com/assets/13426919/18856913/3c0707b2-842d-11e6-8762-53a3eea0d7b6.png)

Here's a concept for the main vehicle

I'm not sure if I hit the whole "low-poly graphics" thing but I tried.

The main cockpit is in a triangular prism (which will allow the user to see what's on their sides), while the main body of the ship is rectangular prism; the front end of the body of the ship is closed into a triangular pyramid.

The jet engine is a trapezoidal prism, while the bottom (where the ship can hover) is a rectangular prism.

The laser cannons are hexagonal prisms which close into a hexagonal pyramid, which is connected to the main body by thin rectangular prisms.

Feedback pls kthx. I'll draw something more detailed if people like this so far.

**Comment by fabulous999** [comment]
working on in now but how should the interior look like should it have a
car wheel or a pilot stick? and do you want me to animate it also?

**Comment by fabulous999** [comment]
btw your image is really good nothing is out of proportion so it easy to
work with but one last request.. is how should the back engine be? (like a
good view from the back) i made this so i am wondering if i made it good (i
can still rework on it if it not it not good)
[image: Inline image 1]

**Comment by fabulous999** [comment]
i'll probably will make  the engine shorter right now

**Comment by fabulous999** [comment]
so here a rough draft version of it tell me if anything need to be change?

[image: Inline image 1]
[image: Inline image 2]
[image: Inline image 3]

**Comment by fabulous999** [comment]
![image 1](https://cloud.githubusercontent.com/assets/13458986/18876146/8e6241c0-8496-11e6-817b-386908070b2f.png)
![image](https://cloud.githubusercontent.com/assets/13458986/18876144/8e5f25f8-8496-11e6-9149-c167a77a85cc.png)
![image 2](https://cloud.githubusercontent.com/assets/13458986/18876145/8e60ae78-8496-11e6-9ccc-3dc048c2dd35.png)

notice that github doesn't show images that was sent via email -_-

**Comment by angelinagutz** [comment]
I have no idea how to reply to comments here :|

Anyway I'm thinking that the back engine should only be on the body and not the cockpit??? So that if the user wants to look back they can and there isn't the engine in the way.

Also, should this ship also have wings? Or is it fine as it is?

**Comment by MWMaresch** [comment]
I think adding wings would be a really good idea if you can make it look more slick and aerodynamic with them.

Also, for the interior, I think just about any direction you take can work out, as long as it's not hyper realistic. You could get really creative with it, or keep it extremely simplistic. There's a different issue for that topic though.

**Comment by angelinagutz** [comment]
I'll see if I can do a concept for the interior as well.

Also, could the wings look something like this? (Bird's eye view)
![something for software project 4](https://cloud.githubusercontent.com/assets/13426919/18935611/306e4734-85af-11e6-8ae5-f05db6599824.png)

**Comment by MWMaresch** [comment]
Yeah I like this design much more than the previous one.

**Comment by fabulous999** [comment]
alright ill finish it all when i get back home from school so around 11 or
12

**Comment by MWMaresch** [comment]
I probably should have closed this awhile ago, as we're beyond this step for the vehicle. Further enhancements belong to #32 .
