### ISSUE TITLE
Create internal vehicle concept art

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Space-Chase-VR#9]

**Comment by angelinagutz** [comment]
![something for software project 5](https://cloud.githubusercontent.com/assets/13426919/18978386/b3c63ae2-8690-11e6-9975-2983079592f1.png)

Could the interior look something like this?

**Comment by fabulous999** [comment]
alright starting to work on it you guys will get the full result tonight

**Comment by fabulous999** [comment]
want me to animate it too?

**Comment by MWMaresch** [comment]
Closing this because further enhancements belong to #32 , and also to show we made progress for the milestone.
